site_name: Venom
repo_url: https://github.com/cadayton/Venom
theme: readthedocs
pages:
  - Home: index.md
  - Installation and Setup:
    - Requirements: Requirements.md
    - Venom Setup: Venom.md
    - XMLDB Setup: XMLDB.md
  - Array cmdlets:
    - Get-VeArrayInfo: Get-VeArrayInfo.md
    - Update-VeArrayInfo: Update-VeArrayInfo.md
  - Cisco cmdlets:
    - Cisco Module: Cisco-Module.md
    - Set-VeDeviceAlias: Set-VeDeviceAlias.md
    - Connect-VeFabric: Connect-VeFabric.md
    - Update-VeFlogi: Update-VeFlogi.md
    - Enable-VePorts: Enable-VePorts.md
  - Pure Storage cmdlets:
    - Get-VePureMetrics: Get-VePureMetrics.md
  - Symmetrix cmdlets:
    - Get-VeSymmMetrics: Get-VeSymmMetrics.md
    - Set-VeSymmLogin: Set-VeSymmLogin.md
    - Find-VeSymmLogins: Find-VeSymmLogin.md
    - Symm Management: Start-SymmMgmt.md
  - Support: Support.md
