site_name: Venom
repo_url: https://github.com/cadayton/Venom
theme: readthedocs
pages:
  - Home: index.md
  - Installation and Setup:
    - Requirements: Requirements.md
    - Venom Setup: Venom.md
    - XMLDB Setup: XMLDB.md
  - CommandLets:
    - Get-VeArrayInfo: Get-VeArrayInfo.md
    - Update-VeArrayInfo: Update-VeArrayInfo.md
    - Get-VeSymmMetrics: Get-VeSymmMetrics.md